GEMINI_API_KEY = "xxxx"

DRIVE_ROOT_FOLDER_ID = "1yD-oiGmEjLr37hMD9b_Z9VzWk0ziI7GS"
GOOGLE_SHEET_ID = "1NuuCMa4-FBrwGVdeeqJp-vRKaKZ4BZXgxC7a8QxDPJM"
GOOGLE_SHEET_TAB_NAME = "Matriz Contratos"


[gcp_service_account]
type = "service_account"
project_id = "basew-de-armot2026"
private_key_id = "a59aef7a8788edb7dc1c4acdaeaa20b822990f14"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDa8j2dm1tv/mHH\n+6yvfwtnl7cAfnXkGcjejf6YeFnksV/p+9JLv8zjaxHPi4/cs44oD9H2b7V6/pUI\nKbuL+93frjUOEXADfWIzA2tAY799HwFI47mDB4plBawKG/GJWGIx5q1Hgwd3ONaU\nsPSRQhLN+M3ofBioy2Dk+IrR8t6AR7CTgqSEVyokaKtxl48rGsvSi2k64yCq0GMU\nWgt5p6VXEmdJNOwMu8aLclfjytHzV6JPAcUSMJLD2gWf+lJtpWBV9CBu8IlZ6qIz\nKLak0UuWG4GP4kESUwWnjImLyeP0Z58sQfQct2lTjhY/gZJ9O4ifNUcbcgIP+OCM\nzqq8/IllAgMBAAECggEAGI9W0RCly6TN5Ch7oP4P0fGHUjNdVxZ7XVexSPorH0e0\nWiNo3h1oRtRyXYUqwJeVqTHJHCtAwMjA//bqdlPs+hPpGKhlF8cfVliaVdE6oDbz\npnEBFM0qPZXKzCGBUSZMcYuOQXjVxA5op6pH7OlsAZXYxyzweTLDLjwhGlbzlZD/\n7bksIkDbZ9rSCZ33RztvGp/Vd4J9Bl3zsPFDHwI6bcT14WQ5ZFR2MgiOpIPCrNPQ\nc9Rvy/LDQf5i30713J2KHvGMaJV0jVlVnWT3uqkp58hpZB/aLY2qVzak6K/m41Od\noekOYzzLfcOLBBhh0WDcI5GylLNWBVdYkyQRilW/WwKBgQD69mdN58gScoU74bP9\nH1MODHDcKvDdSuXaJGQlA02n9WZkrCskTVKsVgGKbbdCVwvheOWfXjRtvAIhjC8h\nQcVdXCrqwiLazWwzKcDChHXimYIOcupy0AA71f2QZHP43/w1mZWaDxZQHMhfvab6\ndi1x6MkqMworVv3JqsMtconAqwKBgQDfV1F+J8xgDKD67Nkt9VRckFtaZojsRTmq\n8g0xysRti8JYBYU8FsBVKfmh+4DhcOyo6Hcm/toZITTsvc34005/CFp6bZZcbQ2F\noPgz70uiEC0cG2jvPVTvA3o/2ZC/szGx6pyZ+kvYIMfPWTgdE5XGd0JoSQ8sETER\nVEazBpp+LwKBgQCekJE05/3BqhoEe9b9V41ikvm8ImWNbIVODzA3Mp8eQC8x7JZV\nmYVi3fSbQjdH8zfOflSXHS6DJwcxqyEcIjJRiqqTKZZcKO70ZK0mOgtB4TwLZRA8\n+q8rH0nWsaGU3fC87Q1ZCa9PbuArneii14hfMHXp89W5DH3NrdckH/ppgQKBgGXJ\nOc6w/KfZmZRCVUhowqXc9IVirYxgkEOkRPcoXhU+2Lec7HfSNp2Zn7d/E+GqwXDJ\nYWRYSbWiOKicaD66rs+eUv3w69H7sWnxTqz8pg+aJ7TjmRNPdGHpx9FJqnpzhHZ9\nYhmaxO4fInERTE2UG3Jz78PvaAbBXwdyzTXSEJ7pAoGBAK8g2IHSnVQEdYAreRux\n4NJkhb5NR++JhQAjLI6BkogRGBJhfQfd1hbU9EULg8i3vpGsHSVAgrt3jY66NGwn\n1hfLv8ChRlwtZExhVlDrhrfqu9p0JNAZPDip65rDZHO+LirPsEWt8rq+XNP08QI+\nNvg4lzo4SiTZ2fS2JACBQIiC\n-----END PRIVATE KEY-----\n"
client_email = "base-de-armot2026@basew-de-armot2026.iam.gserviceaccount.com"
client_id = "114299244065467267693"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/base-de-armot2026%40basew-de-armot2026.iam.gserviceaccount.com"
universe_domain = "googleapis.com"




[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/196Mb2TLJPaO01SwriIIefpjVxj4rOTqV/edit?gid=1746253290#gid=1746253290"
type = "service_account"
project_id = "basew-de-armot2026"
private_key_id = "4cbbd1ce62bebf89a6e37b7b5052d34f96216302"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC+K6kcKVB2c26s
ffQA7YO9dK2cNomch72xPh0E5aUMVRMptVmMMty1IGn/1Pcc02GmuuhexiY2unap
/m9NoEVOcfqBNwI6NUGhRoYgkv6cVayCP2dGTnhUqGH7lIf3r1elRHLHSrhrnuL1
+0FWvEQ/2JCF7gyMGkCM9lFbRmMJfezbn4nb9M0dlJ2uU8mQ9UTTN2A2tT+ZOkri
JIlbL5zTh9N7rBxF/mSzvwd5jIBaGfHEEV2LFhe6nBPCbnc5yeFh+4+AqmdK7/sj
bBLLMUIzZ5HwAHEKZpDmaWvMEXPTSuN+9RKXbIffCXLIOuTrNDbqu71Zx/vZHDgS
41X8DHe/AgMBAAECggEAAT1XnnXGe7JhuxrqR3dE4vjeInG+9xfYOYEmJa05iv/W
K1dufGarrNXHp+gQR4Fsb+6X+F/Ir/w9k2FNNTxUnbl9RvDADiqt56QGC80csitj
MuLzt8mbKMu2l8uhqnbbvQANORW+zgGWVfQlVBace0epT+liIfR2p0FglmLteL2O
gIHKsiEPyTlsbNFZJRMbkgVJkhvZwbJU2p4XHEPfjdNRYCjd+ruMEyEISVkQuoW3
MkobyhS3s+LZ1wALwO8uiwaItnMpIZJlb8wmjvp08K1Ioo8cwzynEfp/BcSVrFlS
3Obxq4GZNt0eFlWtuG1Pk54rrjVmVpgQlWEMJTGmQQKBgQD3TJvwoWT8ZKX/IVMl
cznHOvLuPhnhgfx8ZQY6PQ1WsWXPk1xYIecmKjWiTk/hoMWt3ymmnjQbfKqgsDpJ
AHGfKlXzPUPPT3IeMJ7StE6KpTetC26ocvw6x6ZUn+x9UiJdAHXy9osfOdRv49kf
gmM7jNwGTQiIu+JwEJiuEVoxjQKBgQDE3IA9tenA+HJsychVexBv+Y0UXtOJv3VT
rEC/zblkwX2UhSt88zxkuUrxpSc9pxXfN4nxxy+JyGXeTm/kxIeNmUdTSMADaJlN
uzLo4YsJF+Fx7k8S7dF2lLb8KvELCejCC1D/enzIP51uIHKEYyol9MwAK72vCwG0
cnPuARyNewKBgF0E0OcbHgwdo56qn0bH56S71KKuczeymBEGQuhnDHxeb8g7SpHP
9s0RNWlegYeB3LlA5r7IZRstslSM1O+enh5bY0cB9V6mKGuYqDTjI2PdL2sEkNQF
pEBL1pGgMekVmt1Wjgccm0nci76meoXymnbMzfoEwcAEw/CZHYTj/AQFAoGAez5k
Vr39Yp7n2+2TqthJmSCNTzRykKk5RbHwM2QS7d4oxYN9j1Mj+xb5sUCoyXNCQSWf
Caueuk6oX72RVZIoHuDYA27nLvscBsrse1lAVugJbu83t+0FFozR5hroHvYMLvcw
tVC0sBULdTeBGhqO94ZC9NRtgxmL7rE8nMM7YeMCgYAysJEqMdMQcFYxKwfX5zEv
UNzRF/jjHnRp0ouGZfNtv6AZAa2ry/oyhzT3hkIoFnct//yKVuiHlcp2EYRdEFfN
B5zo3RVWAig44GTu6GIoIDi/hyB+1Gc98r6jQC0vvZw/tAT8VkgivGIvxfNw+7wY
HkloMzdQEFZgL1AXISm30w==
-----END PRIVATE KEY-----"""
client_email = "base-de-armot2026@basew-de-armot2026.iam.gserviceaccount.com"
client_id = "107476833882327978793"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/base-de-armot2026%40basew-de-armot2026.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
