GEMINI_API_KEY = "xxxx"


DRIVE_ROOT_FOLDER_ID = "1yD-oiGmEjLr37hMD9b_Z9VzWk0ziI7GS"
GOOGLE_SHEET_ID = "1NuuCMa4-FBrwGVdeeqJp-vRKaKZ4BZXgxC7a8QxDPJM"
GOOGLE_SHEET_TAB_NAME = "Matriz Contratos"


[gcp_service_account]
type = "service_account"
project_id = "base-de-contratos-armot"
private_key_id = "6f0877677301e944dc4b59ff1d95201654f9938e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCug+pDGXrrkem0
Z5tD9Xe/dl/VNzuU/l/AUG07/fiRatBUsDeqhgpEItYCaIyqYjM7AgcRY5+BkxUm
Ww85R1PpZYhYpsTtqbEOdCUlHH3XITzvspD11Fg5rZJItDZtI3lrILYFUYjO4puX
Bk7AMgp+5j6yCQIX5JuuYRnpBJYO1EYidmCJZejr30pr5zsj9ann/y4urYR3Qz2y
rraOnSWn73XDyNvmI/Vx4iM1Mg7Dx+FVKMxAxDY6YrqUTbZ5UqYfaOOgDi9kMxUh
lrKuSvAUkMYcubbtXlnybaqx25GByFyCbUA+3DO87VbI2Nz9W+TdD4GYM7TIz/4G
Az9jNdkzAgMBAAECggEABvhSz2pBnA4AWQm4TE8OANIgArqJgSpltZ8gtcAvgNNU
zcUZ/BANceo4RPFbCOUSKb2rfZjOgpTWx+jkI0QDiHNbLjs+60UXQr4Fy8UnC4QS
1Hn7yy23dlpF2OyFrfc4PryYOH8oqSao0y/XzlpRS/8zKtYsRLsHMsBDEijyO1ZT
MTmLSjfFJaWJLcXBiOolFkvtxAzppJrYrJyNswXfF2gMEQBXVS0aTOLN9OPUCWdE
UbYdtrcRRZiG+mQHRktv+YASnUOTh8mtUdyLHh5K9A7tkMIRE6VrFyX4ogM+RpvN
eNlUjSa6hlaTID4GQY0pXVeJan9ywL0dYHoGqN455QKBgQDYilVegpixoimxJ6pj
0btVkUtiApWuFm0yym0N+KzXAbIFELXON2Q/dSwMoru8FPH53lrRmQivMgd+xGgd
6FUnzH/+4nlaJJ8ppe9CRDJBUQg6k0wOF6XQdo1X7k3+QcQ1071wRbk8k7rasXkl
ZowawGgYq+RpF+j4wHw9vBuMZQKBgQDOURnE37kt9LNRQNIoFwoQOXUmAa2OJhs2
CufLvQ2WjnXTkuf8ws4KlouoLqBJqZLKE4pnhtfXwNU8aC0Gaq3z/L2OM13jP1ym
hyjJNDcwtcE1vsRg1LHD9rYLd4XrF4Sbl2FJQELVBWQ4n/2F2UbsDJ+1ArhP1FH1
Bv3fexo5twKBgQDICVK/0ik4v7OAIkJ3oAJNE8HtsrGPdsw9xV5lL7qLjNdlcoBh
Fi6XqKieq55+K2M2DsEbKyIopjDiXJJKPpyb/YCod5LfQUF/efjC4LkEOdU+N2Bl
DFdzcnE0L8MBBMQ7bXVtSBvM6DQPXy+o60i2VdRUJkcFBr+DPF4JscJJOQKBgQC0
mzYtq5MVcbJPnKjbw19h2Ip+nNVrLFyBsIY9Sd/NPiRS87T1BSsNBcB3l2llUnZX
Q0fTXK0yB3IjESbpCRYCEet1we2ccukONh80EuuFTnY2MCsEgOykmSG/Y//tTocd
FSVq1EAs7i1PjG6Iby2wkVR1Rk5GQ50DG/29VqwcfQKBgQCrHwkttU3XYUe/FVPm
SY+nBMQqJ2URgrB5MiwiwvQ617lZxRWRf4kDndENNhQDlR2AwKHdSh/jbSo3bWdv
YYv/67iI1Cxa566kBj0gdl9e1Fofk+zyfsZA78QBtwqJkRc7cKtdvtZcSUdmCPhb
+w7sOEo1Fry9ORR8N2vGrVhDGw==
-----END PRIVATE KEY-----"""
client_email = "alejandroarmot@base-de-contratos-armot.iam.gserviceaccount.com"
client_id = "113464081402785390684"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/alejandroarmot%40base-de-contratos-armot.iam.gserviceaccount.com"
universe_domain = "googleapis.com"





[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/196Mb2TLJPaO01SwriIIefpjVxj4rOTqV/edit?gid=1746253290#gid=1746253290"
type = "service_account"
project_id = "basew-de-armot2026"
private_key_id = "4cbbd1ce62bebf89a6e37b7b5052d34f96216302"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC+K6kcKVB2c26s
ffQA7YO9dK2cNomch72xPh0E5aUMVRMptVmMMty1IGn/1Pcc02GmuuhexiY2unap
/m9NoEVOcfqBNwI6NUGhRoYgkv6cVayCP2dGTnhUqGH7lIf3r1elRHLHSrhrnuL1
+0FWvEQ/2JCF7gyMGkCM9lFbRmMJfezbn4nb9M0dlJ2uU8mQ9UTTN2A2tT+ZOkri
JIlbL5zTh9N7rBxF/mSzvwd5jIBaGfHEEV2LFhe6nBPCbnc5yeFh+4+AqmdK7/sj
bBLLMUIzZ5HwAHEKZpDmaWvMEXPTSuN+9RKXbIffCXLIOuTrNDbqu71Zx/vZHDgS
41X8DHe/AgMBAAECggEAAT1XnnXGe7JhuxrqR3dE4vjeInG+9xfYOYEmJa05iv/W
K1dufGarrNXHp+gQR4Fsb+6X+F/Ir/w9k2FNNTxUnbl9RvDADiqt56QGC80csitj
MuLzt8mbKMu2l8uhqnbbvQANORW+zgGWVfQlVBace0epT+liIfR2p0FglmLteL2O
gIHKsiEPyTlsbNFZJRMbkgVJkhvZwbJU2p4XHEPfjdNRYCjd+ruMEyEISVkQuoW3
MkobyhS3s+LZ1wALwO8uiwaItnMpIZJlb8wmjvp08K1Ioo8cwzynEfp/BcSVrFlS
3Obxq4GZNt0eFlWtuG1Pk54rrjVmVpgQlWEMJTGmQQKBgQD3TJvwoWT8ZKX/IVMl
cznHOvLuPhnhgfx8ZQY6PQ1WsWXPk1xYIecmKjWiTk/hoMWt3ymmnjQbfKqgsDpJ
AHGfKlXzPUPPT3IeMJ7StE6KpTetC26ocvw6x6ZUn+x9UiJdAHXy9osfOdRv49kf
gmM7jNwGTQiIu+JwEJiuEVoxjQKBgQDE3IA9tenA+HJsychVexBv+Y0UXtOJv3VT
rEC/zblkwX2UhSt88zxkuUrxpSc9pxXfN4nxxy+JyGXeTm/kxIeNmUdTSMADaJlN
uzLo4YsJF+Fx7k8S7dF2lLb8KvELCejCC1D/enzIP51uIHKEYyol9MwAK72vCwG0
cnPuARyNewKBgF0E0OcbHgwdo56qn0bH56S71KKuczeymBEGQuhnDHxeb8g7SpHP
9s0RNWlegYeB3LlA5r7IZRstslSM1O+enh5bY0cB9V6mKGuYqDTjI2PdL2sEkNQF
pEBL1pGgMekVmt1Wjgccm0nci76meoXymnbMzfoEwcAEw/CZHYTj/AQFAoGAez5k
Vr39Yp7n2+2TqthJmSCNTzRykKk5RbHwM2QS7d4oxYN9j1Mj+xb5sUCoyXNCQSWf
Caueuk6oX72RVZIoHuDYA27nLvscBsrse1lAVugJbu83t+0FFozR5hroHvYMLvcw
tVC0sBULdTeBGhqO94ZC9NRtgxmL7rE8nMM7YeMCgYAysJEqMdMQcFYxKwfX5zEv
UNzRF/jjHnRp0ouGZfNtv6AZAa2ry/oyhzT3hkIoFnct//yKVuiHlcp2EYRdEFfN
B5zo3RVWAig44GTu6GIoIDi/hyB+1Gc98r6jQC0vvZw/tAT8VkgivGIvxfNw+7wY
HkloMzdQEFZgL1AXISm30w==
-----END PRIVATE KEY-----"""
client_email = "base-de-armot2026@basew-de-armot2026.iam.gserviceaccount.com"
client_id = "107476833882327978793"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/base-de-armot2026%40basew-de-armot2026.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
